// Master GenZ IITian Offline Loading Facts Database
// Auto-generated collection of 365 facts categorized by rarity.

enum LoadingFactRarity {
  common,
  rare,
  ultraRare,
}

class LoadingFact {
  final String id;
  final String text;
  final LoadingFactRarity rarity;
  final bool isCoupon;

  const LoadingFact({
    required this.id,
    required this.text,
    required this.rarity,
    this.isCoupon = false,
  });

  Map<String, dynamic> toJson() => {
    'id': id,
    'text': text,
    'rarity': rarity.name,
    'isCoupon': isCoupon,
  };
}

const List<LoadingFact> masterLoadingFacts = [
  LoadingFact(id: '001', text: 'GenZ IITian was founded because IITM BS students needed a better place for studies and information.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '002', text: 'GenZ IITian started with a simple problem: finding the right resources shouldn\'t be this hard.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '003', text: 'What started as a solution to our own problem became a community for thousands of IITM BS students.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '004', text: 'Started with a problem. Accidentally built a community.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '005', text: 'From “Bhai resources kaha milenge?” to building the whole platform.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '006', text: 'Our first goal wasn\'t 25,000 students. It was simply helping the next student.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '007', text: 'GenZ IITian grew this far because someone once mocked the idea. Funny how that worked out.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '008', text: 'Someone once mocked the idea. Anyway… 25,000+ students later. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '009', text: 'GenZ IITian is now a community of 25,000+ students.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '010', text: 'From helping a few students to becoming a 25,000+ student community.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '011', text: '25,000+ students. That escalated quickly.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '012', text: 'We never thought we\'d have our own app. Well… you\'re using it right now.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '013', text: 'This app didn\'t exist when we started. Neither did most of the things we\'ve built today.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '014', text: 'Imagine telling us two years ago that we\'d have our own app. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '015', text: 'Fun fact: you\'re currently waiting for an app that we once never thought we\'d build.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '016', text: 'From an idea to an app to 25,000+ students. We\'re just getting started.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '017', text: 'From an idea → classes → community → 25,000+ students → our own app.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '018', text: 'From classes to courses to community to an actual app. Bro, who allowed this?', rarity: LoadingFactRarity.common),
  LoadingFact(id: '019', text: 'Classes, notes, PYQs, courses, community and now an app. Yeah, things escalated.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '020', text: 'We\'re still building. You\'re literally using part of the journey.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '021', text: 'The version of GenZ IITian you\'re using today isn\'t even close to what we want to build.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '022', text: 'Our next big step? Getting GenZ IITian officially registered as a company.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '023', text: 'Our next side quest: getting GenZ IITian officially registered as a company.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '024', text: 'Built by people who also know the pain of IITM BS.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '025', text: 'Built by people who also understand the pain of IITM BS.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '026', text: 'Some people behind GenZ IITian were once students looking for the exact same help.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '027', text: 'Every class, note and feature exists because an IITM BS student needed it.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '028', text: 'Some of the features you use today started with one student saying, “Can you add this?”', rarity: LoadingFactRarity.common),
  LoadingFact(id: '029', text: 'Every update you see probably started with a problem someone noticed.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '030', text: 'GenZ IITian lore goes deeper than this loading screen.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '031', text: 'A huge part of GenZ IITian will always be about making useful resources accessible.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '032', text: 'Around 90% of the study material on GenZ IITian is completely FREE.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '033', text: 'Around 90% of study material on GenZ IITian is FREE.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '034', text: 'Free One-Shot courses started as a ritual one year ago. We\'re still keeping it alive.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '035', text: 'Free One-Shots became a tradition. At this point, we\'re not allowed to stop.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '036', text: 'Free One-Shots started as a ritual one year ago. The ritual continues. 🫡', rarity: LoadingFactRarity.common),
  LoadingFact(id: '037', text: 'Some of our Term 1 teachers have been with us since we started, almost two years ago.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '038', text: 'Some of our Term 1 teachers have been here since the beginning. OGs fr.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '039', text: 'Different cities. Different backgrounds. One IITM BS community.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '040', text: 'Thousands of students. One very unusual online degree. One community figuring it out together.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '041', text: 'Somewhere, another IITM BS student is probably studying the same topic as you right now.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '042', text: 'GenZ IITian isn\'t built only for students. A lot of it is built because of students.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '043', text: 'There are probably people working on GenZ IITian while you\'re reading this.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '044', text: 'We\'re probably fixing something while you\'re reading this.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '045', text: 'Yes, we also refresh the app after every new update. Just to make sure.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '046', text: 'Building GenZ IITian has mostly been: “What if we add this?” followed by actually adding it.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '047', text: 'We started by helping students. Then somehow we had to start fixing app bugs at 2 AM.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '048', text: 'GenZ IITian: We\'ll keep it simple.\nAlso GenZ IITian: builds another feature.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '049', text: 'We started as a study platform. Why are we debugging Android now? 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '050', text: 'We started as a study platform. Why are we debugging apps now? 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '051', text: 'GenZ IITian roadmap: Finish current features ❌ Get another idea ✅', rarity: LoadingFactRarity.common),
  LoadingFact(id: '052', text: '“Small update.” Developer hasn\'t slept since.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '053', text: 'GenZ IITian has two modes: Shipping features & fixing the features we shipped. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '054', text: 'Shipping features 🤝 fixing the features we shipped.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '055', text: 'Who requested this feature? Actually don\'t answer that.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '056', text: 'We made an app because apparently a website wasn\'t enough.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '057', text: 'Student: Add this feature.\nUs: Good idea.\nDeveloper: 😐', rarity: LoadingFactRarity.common),
  LoadingFact(id: '058', text: 'Our roadmap needs its own roadmap.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '059', text: 'GenZ IITian server seeing End Term approaching: 👁️👄👁️', rarity: LoadingFactRarity.common),
  LoadingFact(id: '060', text: 'If something breaks, it was definitely… Actually, Support Ticket please. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '061', text: '90% resources free. Still gets asked: “Free wala kuch hai?”', rarity: LoadingFactRarity.common),
  LoadingFact(id: '062', text: 'We created One-Shots. Now students think every course should be one shot. We played ourselves. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '063', text: 'GenZ IITian created the discount coupon. GenZ IITian regretted the discount coupon.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '064', text: '25,000+ students. 25,000+ opinions. One support team. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '065', text: 'GenZ IITian trying to make everyone happy: Difficulty: Impossible.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '066', text: 'Assignment khud karlo bhai, loading hum kar dete hain.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '067', text: 'Quiz aa raha hai aur tum loading screen padh rahe ho? 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '068', text: '“Kal se padhunga” — IITM BS student since Week 1.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '069', text: 'Week 1 motivation 🤓 → Week 12 One-Shot 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '070', text: 'Bro opened GenZ IITian. Academic comeback incoming?', rarity: LoadingFactRarity.common),
  LoadingFact(id: '071', text: 'Academic comeback ka Day 1? Again?', rarity: LoadingFactRarity.common),
  LoadingFact(id: '072', text: 'PYQs >>> “I think ye important nahi hai.”', rarity: LoadingFactRarity.common),
  LoadingFact(id: '073', text: 'One-Shot dekh ke “haan bhai syllabus ho gaya” wali feeling.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '074', text: '2× pe lecture dekhna is not a personality trait bro.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '075', text: 'Assignment deadline: 11:59 PM\nStudent at 11:47 PM: 🗿', rarity: LoadingFactRarity.common),
  LoadingFact(id: '076', text: '“Easy course hai bro.”\n— Guy who hasn\'t checked Week 8 yet.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '077', text: 'Quiz ke ek din pehle sab resources important lagne lagte hain.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '078', text: 'IITM BS 🤝 opening 17 tabs before an exam.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '079', text: 'You don\'t need motivation. You need to open the lecture.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '080', text: 'Dashboard load ho raha hai. Syllabus nahi. Woh tumhe karna padega.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '081', text: 'Ek lecture dekhne aaye the. Ab 7 pending dikh gaye. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '082', text: 'Bro really said “iss term Day 1 se padhunga.”', rarity: LoadingFactRarity.common),
  LoadingFact(id: '083', text: 'End Term arc loading…', rarity: LoadingFactRarity.common),
  LoadingFact(id: '084', text: 'One-Shot enjoyer spotted. 👀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '085', text: 'PYQ dekh ke answer yaad aa raha hai = dangerous confidence.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '086', text: 'Padhle bhai. Loading screen kab tak dekhega?', rarity: LoadingFactRarity.common),
  LoadingFact(id: '087', text: 'Bhai attendance hum nahi bacha sakte. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '088', text: 'Course kharidne se syllabus automatically complete nahi hota btw.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '089', text: 'Lecture kholo bhai, guilt nahi.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '090', text: 'Aaj sach mein padhne aaye ho ya bas dashboard dekhne? 👀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '091', text: '“Bas 5 minute Instagram.”\n2 ghante later:', rarity: LoadingFactRarity.common),
  LoadingFact(id: '092', text: 'Mummy ko lag raha hai padh raha hai. Don\'t disappoint her bro. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '093', text: 'Bhai Quiz date check kar lena. Baad mein hume mat bolna. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '094', text: 'One-Shot ko One-Shot hi rehne do. Pura semester replacement mat banao. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '095', text: 'Aaj ka target: lecture complete. Reality: timetable banana.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '096', text: 'Notes download karna ≠ notes padhna.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '097', text: 'Bhai 2× se upar bhi speed chahiye kya? 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '098', text: '“Ye question exam mein thodi aayega.” Famous last words.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '099', text: 'Padhai chal rahi hai? Matlab app toh khol liya…', rarity: LoadingFactRarity.common),
  LoadingFact(id: '100', text: 'Kal exam hai? Welcome back bro. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '101', text: 'Week 12 mein Week 2 search karne wale, we see you. 👀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '102', text: 'GenZ IITian khol diya. Ab bas padhna baaki hai.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '103', text: 'Backlog dekh ke app close mat kar dena bhai. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '104', text: 'Aaj procrastination nahi. Ye message screenshot karke Instagram pe bhi mat jaana.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '105', text: 'Bhai hum resources de sakte hain, exam tumhe hi dena padega.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '106', text: 'Opening the app was step one. Now you actually have to study.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '107', text: 'You opened GenZ IITian instead of Instagram. That\'s already progress.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '108', text: 'Somewhere between Quiz 1 and End Term, everyone becomes serious.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '109', text: 'Loading your dashboard… probably faster than finishing a Statistics assignment.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '110', text: 'Student wants: Live classes ✅ Notes ✅ PYQs ✅ One-Shots ✅ Doubt support ✅\nStudent wants to study: ❌', rarity: LoadingFactRarity.common),
  LoadingFact(id: '111', text: 'Bhai sab kuch provide kar diya. Ab padhna bhi hum hi start karein kya? 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '112', text: '“Notes hain?”\n“PYQs hain?”\n“Recording hai?”\nSab hai bhai. Bas tu nahi padh raha. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '113', text: 'Resources collect karne ki speed: 100. Resources use karne ki speed: 2.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '114', text: 'Bro has every PDF downloaded and zero PDFs opened. 🗿', rarity: LoadingFactRarity.common),
  LoadingFact(id: '115', text: 'Student: Best course chahiye.\nAlso student: Lecture kitne minute ka hai? 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '116', text: 'Timetable banaya? ✅\nNotion setup kiya? ✅\nHighlighter kharida? ✅\nPadhai? kal se.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '117', text: 'Bhai resources ki kami nahi hai. Ab problem kuch aur hai. 👀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '118', text: '“Full syllabus covered hai?”\nBhai pehle Week 1 toh cover kar. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '119', text: 'Student wants everything except the actual lecture.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '120', text: 'Bro wants HD lectures, notes, PYQs, One-Shots, doubt support and mentorship.\nBro\'s contribution: “Kal se pakka.”', rarity: LoadingFactRarity.common),
  LoadingFact(id: '121', text: 'Bro is academically AFK.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '122', text: 'Student downloaded 38 PDFs. Knowledge downloaded: 0 KB.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '123', text: 'Bro\'s CGPA needs a software update.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '124', text: '“Sir important questions bata do.”\nMy brother in Christ, syllabus hi important hai. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '125', text: 'Bro thinks watching the lecture is optional DLC.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '126', text: 'Academic weapon ❌ Academic civilian ✅', rarity: LoadingFactRarity.common),
  LoadingFact(id: '127', text: 'Bro\'s study plan has more seasons than the actual course.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '128', text: 'Student opened Week 1. Aura +1000.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '129', text: '“Easy hai, weekend pe kar lunga.” Canon event detected.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '130', text: 'Bro is cooked but doesn\'t know he\'s cooked yet.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '131', text: 'Student before Quiz: We\'re so back.\nStudent after Quiz: It\'s so over.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '132', text: 'Bro\'s academic comeback has been postponed for maintenance.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '133', text: '“Bas ek doubt hai sir.”\nProceeds to send the entire assignment. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '134', text: 'Student watched 12 minutes of a 2-hour lecture.\n“Concept samajh aa gaya.” 🗿', rarity: LoadingFactRarity.common),
  LoadingFact(id: '135', text: 'Bro speedran the lecture at 2× and retained 0.5×.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '136', text: 'Your syllabus is not gonna mog itself bro.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '137', text: 'Bro got negative academic aura.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '138', text: 'Student: locked in 🔒\nAlso student 4 minutes later: Instagram.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '139', text: 'Bro said “locked in” and immediately took a nap.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '140', text: 'You are not cooked. You are deep-fried.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '141', text: 'Delulu is NOT the solulu for End Term.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '142', text: 'Bro has main-character energy with NPC attendance.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '143', text: '“Trust the process.” WHAT PROCESS BRO? 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '144', text: 'Bro\'s strongest subject is procrastination.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '145', text: 'Downloaded Notes ≠ Completed Notes. We checked the maths.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '146', text: 'Student after missing 14 lectures: “Sir One-Shot kab aayega?” 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '147', text: 'One-Shot was supposed to be revision bro. REVISION. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '148', text: 'Student: Mere marks nahi aa rahe.\nAlso student: 3 lectures watched out of 27.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '149', text: 'Student asking for more material while 47 PDFs are sitting untouched: 🗿', rarity: LoadingFactRarity.common),
  LoadingFact(id: '150', text: 'Bhai pehle jo diya hai woh toh padh le. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '151', text: 'Your backlog has its own backlog.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '152', text: 'At this point your “Watch Later” needs a Watch Later. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '153', text: 'You don\'t have a resource problem. You have a “kal se” problem. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '154', text: 'Bro collects courses like Pokémon.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '155', text: 'Course purchased successfully. Student last seen: 17 days ago. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '156', text: 'Bro purchased the course and went into hibernation.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '157', text: 'Payment: Successful ✅\nAcademic comeback: Pending…', rarity: LoadingFactRarity.common),
  LoadingFact(id: '158', text: 'Course kharidne ke baad gayab hone wale students, attendance lagao. 👀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '159', text: 'Bro bought the course like it was a gym membership. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '160', text: 'Purchase course → Watch 1 lecture → Disappear → Return before End Term. The cycle continues.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '161', text: 'Your course missed you bro.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '162', text: 'Course: “He\'ll come back.”\nStudent: 😴', rarity: LoadingFactRarity.common),
  LoadingFact(id: '163', text: 'Buying the course was Step 1. Unfortunately, there are more steps. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '164', text: 'Bro thought payment automatically transfers knowledge.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '165', text: 'Course purchase karte waqt motivation 📈\n3 din baad motivation 📉', rarity: LoadingFactRarity.common),
  LoadingFact(id: '166', text: 'Don\'t worry. Your untouched course is safe with us. 🫡', rarity: LoadingFactRarity.common),
  LoadingFact(id: '167', text: 'Bro opened the app after 21 days and expected us not to notice. 👀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '168', text: 'You bought the course.\nThe course believed in you.\nWhat happened bro? 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '169', text: 'Student: Course FREE kar do. 🥺\nTeacher: Salary? 🥺\nGenZ IITian in the middle: 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '170', text: 'Student wants FREE course. Teacher wants payment. Server wants money. Hum karein toh karein kya? 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '171', text: 'Student: ₹0 please.\nTeacher: ₹₹₹ please.\nGenZ IITian: understandable, have a nice day. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '172', text: '“Bhai free mein de do.”\nServer bill has entered the chat.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '173', text: 'Students 🤝 Teachers\nBoth asking GenZ IITian for money in opposite directions. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '174', text: '90% free resources ke baad bhi:\n“Bhai ye wala bhi free kar do na.” 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '175', text: 'Teacher salary + Server bill + Free courses = Maths 2 ka hardest question.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '176', text: 'Student: Discount?\nUs: Already discounted.\nStudent: Aur discount? 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '177', text: 'BAHII kuch dikkat hai toh Support Ticket raise kar de. Aise gussa mat ho. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '178', text: 'App mein problem? Ticket raise kar bhai. 1-star review se developer ko telepathy nahi aati. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '179', text: 'Bhai pehle Support Ticket. Gussa baad mein. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '180', text: 'Something broken? Tell support. Phone todne se bug fix nahi hoga.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '181', text: '“WORKING NAHI HAI 😡”\nBhai screenshot bhi bhej de. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '182', text: 'Support: “Please explain the issue.”\nStudent: “Nahi chal raha.” 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '183', text: 'Bug mila? Congratulations QA Engineer. Ab ticket bhi raise karde.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '184', text: 'Bhai issue bata de properly. “Problem hai” se debugging thodi hogi. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '185', text: 'Manager\'s most-used words: “Bhai screenshot bhejo.”', rarity: LoadingFactRarity.common),
  LoadingFact(id: '186', text: 'Discount coupons might be GenZ IITian\'s most-used feature. Our finance team knows. 💀', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '187', text: 'You guys REALLY like discount codes. 😭', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '188', text: 'GenZ IITian students when they see “Apply Coupon”: 👁️👄👁️', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '189', text: 'We may or may not have lost thousands because of discount coupons. 💀', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '190', text: 'Student sees ₹299 ❌\nStudent sees ₹399 + 25% OFF ✅', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '191', text: 'Some of you remember coupon codes better than Statistics formulas. 😭', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '192', text: 'Coupon code expired.\nStudent: betrayal, heartbreak, pain.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '193', text: '“Any coupon available?”\nBro hasn\'t even selected the course yet. 💀', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '194', text: 'Our most powerful marketing department might just be the coupon box.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '195', text: 'Psst… use code `GENZ23` for 25% OFF.\nYou weren\'t supposed to find this. 👀', rarity: LoadingFactRarity.ultraRare, isCoupon: true),
  LoadingFact(id: '196', text: 'RARE DROP 🚨\n`GENZ23` → 25% OFF\nNow pretend you never saw this.', rarity: LoadingFactRarity.ultraRare, isCoupon: true),
  LoadingFact(id: '197', text: 'Secret coupon unlocked.\n`GENZ23`\n25% OFF.\nScreenshot fast. 👀', rarity: LoadingFactRarity.ultraRare, isCoupon: true),
  LoadingFact(id: '198', text: 'Hold up bro, we\'re cooking.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '199', text: 'Let him load.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '200', text: 'Loading… because apparently teleportation isn\'t supported yet.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '201', text: 'Server be like: 2 min bhai aa raha hu.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '202', text: 'Your dashboard is being summoned.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '203', text: 'Wait wait wait… almost cooked.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '204', text: 'Fetching your stuff. Don\'t rage quit yet. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '205', text: 'Loading… Trust the process bro.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '206', text: 'App: loading\nYou: 👁️👄👁️', rarity: LoadingFactRarity.common),
  LoadingFact(id: '207', text: 'Bro it\'s been 0.7 seconds. Chill.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '208', text: 'Loading your academic responsibilities… unfortunately.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '209', text: 'We\'re cooking your dashboard. Don\'t enter the kitchen.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '210', text: 'Connecting to the academic multiverse…', rarity: LoadingFactRarity.common),
  LoadingFact(id: '211', text: 'Wait, backend bhai kuch kar raha hai.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '212', text: 'Loading ███████░░\nSource: trust me bro.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '213', text: 'This message exists because a normal loading spinner was too boring.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '214', text: 'We could\'ve just written “Loading…” here. But where\'s the fun in that?', rarity: LoadingFactRarity.common),
  LoadingFact(id: '215', text: 'No motivational quote here. Your dashboard is loading.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '216', text: 'Bro got Fanum taxed by the syllabus.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '217', text: 'Skibidi ❌\nStudy-bidi ✅', rarity: LoadingFactRarity.common),
  LoadingFact(id: '218', text: 'Bro thinks he\'s sigma until Statistics 2 pulls up.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '219', text: 'Only in IITM BS 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '220', text: 'Bro\'s academic aura just dropped by 7000.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '221', text: 'No amount of rizz can save this attendance.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '222', text: 'Bro tried to rizz the examiner with handwriting.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '223', text: 'Your backlog is low-key mogging you.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '224', text: 'Bro thinks he\'s the final boss.\nWeek 12: Allow me to introduce myself.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '225', text: 'Sigma grindset:\nOpen lecture → actually finish lecture.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '226', text: 'Bro got humbled by a 1-mark question.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '227', text: 'That answer was NOT giving. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '228', text: 'Chat, are we cooked?\nYes. Next question.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '229', text: 'Bro is fighting for his life against a PDF.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '230', text: 'Infinite aura ❌\nInfinite backlog ✅', rarity: LoadingFactRarity.common),
  LoadingFact(id: '231', text: 'Academic weapon ❌\nAcademic civilian ✅', rarity: LoadingFactRarity.common),
  LoadingFact(id: '232', text: 'Bro got negative academic aura.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '233', text: 'Beta padhai kar lo, ye mobile kuch nahi rakha.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '234', text: 'Hamare zamane mein One-Shot nahi hota tha. 🗿', rarity: LoadingFactRarity.common),
  LoadingFact(id: '235', text: '₹299 ka course le liya hai toh pura dekho beta.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '236', text: 'Papa: Padhai kaisi chal rahi hai?\nYou: Haan badhiya.\nDashboard: 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '237', text: '“Phone band karo aur kitab kholo.”\nRare Gen-X wisdom unlocked.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '238', text: 'Hamare time pe 2× nahi tha. Teacher ki speed pe hi padhna padta tha.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '239', text: 'Beta marks coupon code se discount nahi hote.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '240', text: 'Itne resources diye hain. Ab aur kya chahiye beta?', rarity: LoadingFactRarity.common),
  LoadingFact(id: '241', text: 'GenZ IITian temporarily became GenX IITian. Please study.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '242', text: 'Teacher: “Bas 1 hour ki class hogi.”\nNarrator: It was not 1 hour.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '243', text: 'Teacher: “Ye basic hai.”\nEntire class: 👁️👄👁️', rarity: LoadingFactRarity.common),
  LoadingFact(id: '244', text: 'Teacher: Any doubts?\nStudents: silence.\nWhatsApp 7 minutes later: SIRRR DOUBT 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '245', text: 'Teacher explaining for the fourth time: 🙂', rarity: LoadingFactRarity.common),
  LoadingFact(id: '246', text: 'Teacher: “Isko hum already discuss kar chuke hain.”\nStudent who joined 4 minutes ago: Sir once more?', rarity: LoadingFactRarity.common),
  LoadingFact(id: '247', text: 'Teacher uploaded 73 pages of notes and called them “short notes.” 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '248', text: 'Teacher: This won\'t take much time.\n2 hours later…', rarity: LoadingFactRarity.common),
  LoadingFact(id: '249', text: 'Teacher after saying “very easy question”: destroys everyone\'s confidence.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '250', text: 'Teacher: Please revise before next class.\nStudents collectively: absolutely not.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '251', text: 'Teacher seeing “Sir recording?” after teaching LIVE for 2 hours: 🗿', rarity: LoadingFactRarity.common),
  LoadingFact(id: '252', text: 'Teacher: “Attendance is important.”\nStudent joins Meet and disappears into another dimension.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '253', text: 'Teacher\'s biggest opp: students asking “Exam mein aayega?”', rarity: LoadingFactRarity.common),
  LoadingFact(id: '254', text: 'Teacher preparing full lecture.\nStudent waiting for One-Shot. 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '255', text: 'Teacher explaining concept deeply.\nChat: “Sir PDF?”', rarity: LoadingFactRarity.common),
  LoadingFact(id: '256', text: 'Teacher: Any questions?\nOne student: Sir course kab expire hoga? 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '257', text: 'Student wants free course.\nTeacher wants payment.\nDeveloper wants requirements.\nManager: 🙂', rarity: LoadingFactRarity.common),
  LoadingFact(id: '258', text: 'Manager managing 25,000+ students:\n“Yeah bro everything is under control.”\nNothing is under control. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '259', text: 'Student: Sir course?\nTeacher: Payment?\nDeveloper: Bug?\nManager: BHAIIII 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '260', text: 'That one manager handling students, teachers, support and developers simultaneously: 🗿', rarity: LoadingFactRarity.common),
  LoadingFact(id: '261', text: 'Manager woke up.\n47 messages.\nGood morning. ❤️', rarity: LoadingFactRarity.common),
  LoadingFact(id: '262', text: 'Manager\'s Screen Time: Don\'t ask.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '263', text: 'Student sends “Hi”.\nManager replies.\nStudent disappears for 6 hours. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '264', text: 'Manager: Please raise a support ticket.\nStudent: Sir actually problem ye hai…\nManager: 😭', rarity: LoadingFactRarity.common),
  LoadingFact(id: '265', text: 'Teacher calling.\nStudent calling.\nDeveloper calling.\nManager considering airplane mode.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '266', text: 'Manager solved one problem.\nThree new problems spawned.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '267', text: 'Manager after finally clearing WhatsApp:\n*new message*\n“Sir ek doubt tha…”', rarity: LoadingFactRarity.common),
  LoadingFact(id: '268', text: 'Manager: Today I\'ll focus on one thing.\nUniverse: absolutely not.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '269', text: 'Students think manager is customer support.\nTeachers think manager is HR.\nDevelopers think manager is product manager.\nManager doesn\'t know anymore. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '270', text: 'Manager typing “Sure, I\'ll check” for the 83rd time today.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '271', text: 'Manager when someone says “small issue hai”: 👁️👄👁️', rarity: LoadingFactRarity.common),
  LoadingFact(id: '272', text: 'One manager.\n25,000 students.\nSeems balanced. 👍', rarity: LoadingFactRarity.common),
  LoadingFact(id: '273', text: 'Manager finally sleeps.\nServer: Hey.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '274', text: 'Manager isn\'t online.\nManager is ALWAYS online.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '275', text: 'Manager\'s notification bar needs therapy.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '276', text: 'Student: Urgent sir!!!\nIssue: Forgot password. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '277', text: 'Manager reading a 14-line message that could\'ve been “I can\'t login.”', rarity: LoadingFactRarity.common),
  LoadingFact(id: '278', text: 'Manager after saying “last task for today” at 11 PM: 🤡', rarity: LoadingFactRarity.common),
  LoadingFact(id: '279', text: 'Manager has left the chat.\nManager has been added back to the chat.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '280', text: 'Manager doesn\'t need coffee.\nManager needs fewer notifications.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '281', text: 'Gen Alpha: Skibidi sigma aura.\nGen Z: Bro I\'m cooked.\nMillennial: I need coffee.\nGen X: PHONE BAND KARO.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '282', text: 'Gen Z student: I\'m cooked.\nGen X parent: Toh padhai karo.\nProblem solved. 🗿', rarity: LoadingFactRarity.common),
  LoadingFact(id: '283', text: 'Gen Alpha wants aura.\nGen Z wants peace.\nTeacher wants attendance.\nManager wants everyone to stop texting for 5 minutes.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '284', text: 'Student: delulu is the solulu.\nTeacher: No, revision is the solution.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '285', text: 'Gen Z: Mental health break.\nGen X dad: Abhi toh padhna start kiya tha? 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '286', text: 'Gen Alpha: +100 aura\nTeacher: +10 marks\nChoose wisely.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '287', text: 'Gen Z invented “I\'m cooked” because “maine padhai nahi ki” was too long.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '288', text: 'Exam tomorrow? Suddenly GenZ IITian looking beautiful huh? 😭', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '289', text: 'Welcome back, seasonal student.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '290', text: 'One-Shot servers preparing for war. 🫡', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '291', text: 'PYQ hunters have entered the chat.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '292', text: 'Exam season detected. Panic mode: ON.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '293', text: '3 months ka syllabus.\n1 night.\nUnlimited confidence. 🗿', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '294', text: '“Kitna hua?”\n“Bas start kar raha hu.” 💀', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '295', text: 'If you\'re seeing this at 3 AM before the exam… bhai.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '296', text: 'Don\'t calculate required marks right now. Just study. 😭', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '297', text: 'Suddenly everyone wants Week 1–12 notes. Interesting. 👀', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '298', text: 'Academic comeback speedrun begins NOW.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '299', text: 'One-Shot → PYQ → Bhagwan bharose.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '300', text: 'Exam arc is getting serious.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '301', text: 'You had the whole term btw. 💀', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '302', text: 'All the best bhai. Ab genuinely padhle. ❤️', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '303', text: 'You actually read loading-screen facts? Respect.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '304', text: 'Still loading? Okay… this fact wasn\'t supposed to get this much screen time.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '305', text: 'You found a rare loading message. There is absolutely no reward for this.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '306', text: 'Plot twist: the app finished loading while you were reading this.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '307', text: 'If you\'ve seen this message five times, you probably open GenZ IITian a lot.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '308', text: 'Okay, enough facts. Let\'s study.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '309', text: 'This loading message has zero academic value.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '310', text: 'Developer was probably bored when he added this.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '311', text: 'Manager approved this message. Probably without reading it. 💀', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '312', text: 'Teacher doesn\'t know we put this here. Don\'t snitch.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '313', text: 'Screenshot this and send it to the group without context.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '314', text: 'Touch grass ❌\nTouch syllabus ✅', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '315', text: 'This message exists because a normal loading spinner was too boring.', rarity: LoadingFactRarity.rare),
  LoadingFact(id: '316', text: 'BAHIIII…', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '317', text: 'Bhai?', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '318', text: 'BHAIIII SUNNNN 😭', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '319', text: 'Woh… main abhi bhi dikh raha hu kya? 👀', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '320', text: 'Bhai loading ho gaya kya?\n…\nBhai?', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '321', text: 'BAHIII sun na…\nTu loading screen seriously padh raha hai? 💀', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '322', text: 'Bhai ek baat bolu?\nRehne de. Padhai kar.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '323', text: 'Bhai bhai bhai…\nQuiz kab hai pata hai na? 👀', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '324', text: 'Sun bhai…\nBacklog check kiya recently?', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '325', text: 'BHAIII!\nOh, you\'re still here. Awkward.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '326', text: 'Bhai agar ye message teesri baar dikh raha hai toh app nahi, internet check kar. 😭', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '327', text: 'Bhai…\nwoh pending lecture abhi bhi pending hai. 💀', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '328', text: 'Bhai sun…', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '329', text: 'Closer…', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '330', text: 'Aur paas… 👀', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '331', text: 'BHAI PADHLE. 💀', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '332', text: 'BAHII bahaiii sun… woh abhi bhi dikh raha hu kya? 👀', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '333', text: 'Achievement unlocked: Loading Screen Reader.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '334', text: '1% chance message. Congrats. Kuch mila nahi though.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '335', text: 'You found an Easter egg! 🥚\nReward: +0 CGPA.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '336', text: 'Secret message unlocked.\nNow go study.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '337', text: 'You actually stayed long enough to read this. 💀', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '338', text: 'Screenshot this. Nobody will believe you found the rare message.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '339', text: 'There are more secret messages.\nOr maybe there aren\'t. 👀', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '340', text: 'Extremely rare GenZ IITian lore discovered.\n+100 aura.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '341', text: 'You found this message before completing your pending lecture. Crazy.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '342', text: 'Achievement unlocked: Professional Procrastinator.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '343', text: 'Loading screen lore > syllabus lore apparently.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '344', text: 'Rare drop: +500 aura.\nCGPA remains unchanged.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '345', text: 'You\'ve unlocked GenZ IITian brainrot mode.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '346', text: 'This message has a 0.1% spawn rate.\nStill no reward.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '347', text: 'Developer put this here at an unreasonable hour.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '348', text: 'Why are you still reading this 😭', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '349', text: 'Bro found message #300 instead of completing Lecture #3. 😭', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '350', text: 'This message has zero academic value.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '351', text: 'Achievement unlocked: Professional Procrastinator.', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '352', text: 'Teacher doesn\'t know we put this here. Don\'t snitch. 👀', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '353', text: 'Manager approved this message. Probably without reading it. 💀', rarity: LoadingFactRarity.ultraRare),
  LoadingFact(id: '354', text: '“Sir recording mil jayegi?”\nRecording milne ke baad: never opens it. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '355', text: 'One-Shot was supposed to be revision bro. REVISION.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '356', text: 'Student: Mere marks nahi aa rahe.\nAlso student: 3 lectures watched out of 27.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '357', text: 'Your backlog has its own backlog.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '358', text: 'At this point your Watch Later needs a Watch Later. 💀', rarity: LoadingFactRarity.common),
  LoadingFact(id: '359', text: 'Course purchase karte waqt motivation 📈\n3 din baad motivation 📉', rarity: LoadingFactRarity.common),
  LoadingFact(id: '360', text: 'Bro collects courses like Pokémon.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '361', text: 'Bro bought the course like it was a gym membership.', rarity: LoadingFactRarity.common),
  LoadingFact(id: '362', text: 'Your untouched course is safe with us. 🫡', rarity: LoadingFactRarity.common),
  LoadingFact(id: '363', text: 'You bought the course. The course believed in you. What happened bro?', rarity: LoadingFactRarity.common),
  LoadingFact(id: '364', text: 'Student asking for more material while 47 PDFs are sitting untouched: 🗿', rarity: LoadingFactRarity.common),
  LoadingFact(id: '365', text: 'Bhai pehle jo diya hai woh toh padh le. 😭', rarity: LoadingFactRarity.common),
];
